// Single source of truth for the public bid URL shape.
//
// Shape: /bids/<slug>/<code>
//   - <slug>  alphanumeric + hyphens, generated by Phase 3's
//             generate_bid_slug() Postgres function.
//   - <code>  32-byte base64url access code minted by create-public-booking.
//             The code is a path segment (not a query string) so it does
//             not leak in the Referer header when the bid page links to
//             third parties (maps, calendar, etc.).
//
// Callers:
//   - src/services/bookings/create-public-booking.ts (returns the URL to
//     redirect to after submit)
//   - app/(public)/bids/[slug]/[code]/page.tsx (parses route params)
//   - App 8 email templates (later — embed in the confirmation email,
//     use buildAbsoluteBidUrl() so the link survives an email client)
//
// Per-property domains (intake.rhythm.co / members.horseshoebaysportingclub.com /
// etc. from build proposal §14) are deferred until Q11 lands. Until then,
// every bid lives on the single Vercel domain.
//
// The slug + access-code chars (alphanumerics, '-', '_') are all URL
// path-safe, so no encoding is needed today. encodeURIComponent() is
// applied anyway as a forward-safety belt — if generate_bid_slug() ever
// gains unicode or the access-code alphabet expands, the URL contract
// keeps working without a hunt-and-fix sweep.

export const BID_PATH_PREFIX = "/bids";

export interface BidUrlParams {
  slug: string;
  code: string;
}

export function buildBidUrl(slug: string, code: string): string {
  return `${BID_PATH_PREFIX}/${encodeURIComponent(slug)}/${encodeURIComponent(code)}`;
}

// Absolute URL for email templates and any out-of-app share surface.
// `origin` should be the scheme+host (e.g. "https://rhythm.co" or
// "https://intake.rhythm.co"); a trailing slash is tolerated.
export function buildAbsoluteBidUrl(
  origin: string,
  slug: string,
  code: string,
): string {
  return `${origin.replace(/\/+$/, "")}${buildBidUrl(slug, code)}`;
}

// Narrows Next.js `params` (after `await`) to the shape the bid page
// needs. Returns null when either field is missing or blank — callers
// should 404 on null (don't leak slug existence with a 400/401).
export function parseBidUrlParams(input: {
  slug?: unknown;
  code?: unknown;
}): BidUrlParams | null {
  if (typeof input.slug !== "string" || typeof input.code !== "string") {
    return null;
  }
  const slug = input.slug.trim();
  const code = input.code.trim();
  if (!slug || !code) return null;
  return { slug, code };
}
